### ISSUE TITLE
Open in background is based on Cmd key which introduces conflicts

### ISSUE THREAD

**Issue by al3xandru** [Appccessibility-Shox/Keys#28]
The open in background feature is hardcoded to use `Cmd` + Keys key. I don't think there are many unbound `Cmd+key` shortcuts and thus the feature of opening in background is very hard to be used. Can you please consider using another modifier key?

**Comment by patrickshox** [comment]
Possibly in the future.

**Comment by martinfjant** [comment]
I've tried several variations of the cmd+something and none of them seem to work :S

**Comment by patrickshox** [comment]
Did you enable that option by checking the checkbox in the app?
