### ISSUE TITLE
Use non-alphanumeric keys for Activation Key

### ISSUE THREAD

**Issue by theamazingcase** [Appccessibility-Shox/Keys#35]
I'd really like to set the activation key to \ or / possibly. I use these keys for a fair amount of activations for other apps and instinctively go there. Current preferences pane won't let me use those.

**Comment by patrickshox** [comment]
Good idea! I've updated the MacOS and iPadOS versions to allow forward and back slashes to be used as the activation key. I don't think I want to allow just any key to be used, however.

https://github.com/Appccessibility-Shox/Keys/blob/a6cf9276f4d6840cb833fbbea002615be8f03244/macOS%20(App)/ViewController.swift#L92-L96

https://github.com/Appccessibility-Shox/Keys/blob/88e738c73021ff8bab66d930101c433fab655ba8/iOS%20(App)/ActivationKeyPopupView.swift#L103-L107
