### ISSUE TITLE
Where are the preferences?

### ISSUE THREAD

**Issue by tiktuk** [Appccessibility-Shox/Keys#36]
This is probably really obvious but I can't figure out where the preferences are?

In the Safari preferences I can only disable and enable Keys.

It's great so far, though :) .

**Comment by patrickshox** [comment]
No worries! Unlike how extensions for other browsers work, all Safari extensions come bundled with applications. If you search your applications folder you'll find the Keys app where all the preferences can be adjusted
<img width="946" alt="Screen Shot 2021-12-29 at 3 50 59 AM" src="https://user-images.githubusercontent.com/47332449/147644081-ef0ad288-8a60-452c-a929-11a425040807.png">
.

**Comment by tiktuk** [comment]
Got, it, thanks!
